name: GitHub Action Demo
on: 
  # 当执行 `push` 或 ·pull_request` 时就触发工作流的执行，这里仅针对 `main` 分支
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
# 工作流由一个或多个作业（job）组成，这些作业可以顺序运行也可以并行运行
jobs:
  # 当前的工作流仅包含一个作业，作业ID是"build"
  build:
    # 作业名称
    name: build demo actions
    # 执行作业所需的运行器 ubuntu
    runs-on: ubuntu-latest
    
    # steps 代表了作业中包含的一系列可被执行的任务
    steps:
      # 在 $GITHUB_WORKSPACE 下 checks-out 当前仓库，这样当前作业就可以访问该仓库
      - uses: actions/checkout@v2
      
      # 使用运行器的终端运行一条命令
      - name: Run a one-line script
        run: echo Hello, world!
      
      # 使用运行器的终端运行一组命令
      - name: Run a multi-line sciprt
        run: |
          echo add other actions to build,
          echo test, add depoly your project
