# 工作流名称
name: Github-Profile-Summary-Cards

on:
  schedule:
    # 每24小时触发一次
    - cron: "* */24 * * *"
  # 开启手动触发
  workflow_dispatch:
  
jobs:
  # job id
  build:
    runs-on: ubuntu-latest
    name: generate
      
    steps:
      # 第一步，checkout 当前项目
      - uses: actions/checkout@v2
        
      # 第二步，引入目标 action: vn7n24fzkq/github-profile-summary-cards仓库中的 `release` 分支
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.README }}
        with:
          USERNAME: ${{ github.repository_owner }}
